### PR TITLE
Markdown header margin fix [Fixes #83]

### LINKED ISSUE #83: [UI bug] - Too much spacing between markdowns sections on developer docs
- The spacing between sections of the developer docs is too large. 
- [The Figma file specifies 64px between the final element and the next H2](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1578%3A19042&t=IM0cQlwLjB4YYIVG-1)
- We've got 92px margin between last paragraph and start of the next heading (28px bottom + 64px top). 

These margins should collapse:

image

image

image

This is especially pronounced on mobile: 

image

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Switches container for markdown content to a Box instead of a flex Stack
- This allows the vertical margins of the markdown content to properly collapse into one another when stacked
- Reduced top margin to 3rem for h2's on mobile

While working in the MDComponents file, also noticed a good amount of redundant code from recently parsing header ids from the MD content.
- I updated the `parseHeadingIds` function to always return an object with `children, title, headingId`
- If there is no "{#...}" found, added a function to parse out a kebab-case header id based on the title, and return that with an object
- By always returning an object with an ID, was able to then remove the conditional code in MDComponents.

## Screenshots
image

image

## Preview link
https://deploy-preview-120--melodious-puffpuff-8e1109.netlify.app/docs

## Related issue
- [Fixes #83]

### CODE REVIEW

File: src/utils/parseHeadingId.ts [hunk 1]
```diff
@@ -1,18 +1,25 @@
 const check = '{#';
 
-export const parseHeadingId = (children: string[]) => {
-  if (children[children.length - 1].includes(check)) {
-    const temp = children[children.length - 1].split(check);
-    const headingId = temp[temp.length - 1].split('}')[0];
-
-    children[children.length - 1] = temp[0];
+const nameToKebabCase = (name: string): string =>
```
Comment (nhsz) [inline src/utils/parseHeadingId.ts:3]: should be moved to a separated util function

**Review by nhsz — CHANGES_REQUESTED** [review]
Awesome @wackerow good job, thx for the refactor! Asked for a small changed and is good to go

File: src/utils/parseHeadingId.ts [hunk 2]
```diff
@@ -1,12 +1,6 @@
...
+import { getKebabCaseFromName } from './';
 
-const nameToKebabCase = (name: string): string =>
-  name
-    .replace(/[#]/g, '')
-    .trim()
-    .toLowerCase()
-    .replace(/ /g, '-')
-    .replace(/[^a-z0-9-]/g, '');
+const check = '{#';
```
Comment (nhsz) [inline src/utils/parseHeadingId.ts:3]: any reason to define `check` as a global var here?

Comment (wackerow) [reply src/utils/parseHeadingId.ts:3]: Good question. That was there before I just left it.. I'm not sure it really needs to be global honestly since it's a pretty specific use case.

File: src/pages/[...slug].tsx [hunk 3]
```diff
@@ -116,17 +116,20 @@ const DocPage: NextPage<Props> = ({ frontmatter, content, navLinks, lastModified
             </Stack>
 
             <Flex width='100%' placeContent='space-between' gap={8}>
-              <Stack maxW='768px' sx={{ "*:first-of-type": { marginTop: '0 !important' } }}>
+              <Box maxW='768px' sx={{ '*:first-child': { marginTop: '0 !important' } }}>
```
Comment (wackerow) [inline src/pages/[...slug].tsx:119]:
```suggestion
              <Box maxW='768px' sx={{ '*:first-of-type': { marginTop: '0 !important' } }}>
```

File: src/utils/parseHeadingId.ts [hunk 4]
```diff
@@ -1,18 +1,23 @@
+import { getKebabCaseFromName } from './';
+
 const check = '{#';
```
Comment (nhsz) [inline src/utils/parseHeadingId.ts:3]: should be defined inside the function

**Review by nhsz — CHANGES_REQUESTED** [review]

File: src/utils/parseHeadingId.ts [hunk 5]
```diff
@@ -1,18 +1,23 @@
...
 
 export const parseHeadingId = (children: string[]) => {
-  if (children[children.length - 1].includes(check)) {
-    const temp = children[children.length - 1].split(check);
-    const headingId = temp[temp.length - 1].split('}')[0];
-
-    children[children.length - 1] = temp[0];
-
+  const lastChild = children[children.length - 1];
+  const split = children[children.length - 1].split(check);
```
Comment (corwintines) [inline src/utils/parseHeadingId.ts:7]:
```suggestion
  const split = lastChild.split(check);
```

**Review by corwintines — APPROVED** [review]

**Review by nhsz — APPROVED** [review]
LGTM, thx for the fix!
