### PR TITLE
fix: buttons :active/:focus styles

### LINKED ISSUE #162: [DESING BUG] Focus in the download buttons on dark mode
Focus on the download buttons in dark mode should have different colors.

screenshot from the deployment preview
Screen Shot 2022-12-14 03 08 20 PM

screenshot from the design system.
Screen Shot 2022-12-14 03 10 27 PM

### PR DESCRIPTION
**Pull request by nhsz**
This PR fixes #162

### CODE REVIEW

File: src/theme/components/Button.ts [hunk 1]
```diff
@@ -1,35 +1,28 @@
...
-      width: { base: '188px', md: 'auto' },
-      bg: 'primary',
-      _hover: { bg: 'secondary' },
-      _focus: {
-        bg: 'primary',
-        boxShadow: 'inset 0 0 0 2px var(--chakra-colors-green-200) !important'
-      },
-      _active: { borderTop: '4px solid', borderColor: 'green.200' }
+      ...primary,
+      _active: { borderTop: '4px solid', borderColor: 'primary', pt: '4px', bg: 'secondary' }
```
Comment (corwintines) [inline src/theme/components/Button.ts:25]: Is this needed if this style is in primary above?

Comment (nhsz) [reply src/theme/components/Button.ts:25]: Thx for catching, not needed, updated

**Review by wackerow — APPROVED** [review]
