### PR TITLE
Fix spacing for DocumentNav links [Fixes #87]

### LINKED ISSUE #87: [UI bug] - Incorrect spacing on docs table of contents
- Spacing between elements on the table of contents is currently 24px
- The design specifies 14px

image

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Used a Box instead of flex Stack for right document nav items to allow vertical margins of children to properly collapse into one another
- Reduces padding between items to 14px per design spec

## Screenshot
image

## Preview link
https://deploy-preview-122--melodious-puffpuff-8e1109.netlify.app/docs

## Related issue
- [Fixes #87]

### CODE REVIEW

File: src/components/UI/docs/DocumentNav.tsx [hunk 1]
```diff
@@ -32,13 +32,14 @@ export const DocumentNav: FC<Props> = ({ content }) => {
               <Text
                 color={activeHash === heading?.headingId ? 'body' : 'primary'}
                 textStyle='document-nav-link'
+                mb='14px'
```
Comment (corwintines) [inline src/components/UI/docs/DocumentNav.tsx:35]:
```suggestion
```

I think this can be removed and just update the `document-nav-link` style in `textStyles.ts`

Can be updated to: 
```
'document-nav-link': {
    fontFamily: 'body',
    fontWeight: 400,
    fontSize: '13px',
    lineHeight: 5,
    letterSpacing: '1%',
    mb: 3.5
  },
  ```
  
  3.5 is 14px so using that. Its currently 4 and that should be updated.

Comment (wackerow) [reply src/components/UI/docs/DocumentNav.tsx:35]: Not necessarily against, but we don't declare margins in any of the other textStyles, which is why I left this local to the component. Do we want to be moving margins to this file? In this case it doesn't seem to make a difference since the `document-nav-link` style is only used here, but just noting.

As an alternative:
```suggestion
                mb={3.5}
```

Comment (wackerow) [reply src/components/UI/docs/DocumentNav.tsx]: Ah, okay yeah, overlooked that the `mb: 4` was already there... but yeah, similar to last comment, I think it makes a bit more sense to not mix in margins to the textStyles file unless we're going to be more consistent with it. ... I'll add a commit and push.

Comment (wackerow) [reply src/components/UI/docs/DocumentNav.tsx]: nm... would approve but it's my PR

**Review by nhsz — APPROVED** [review]
Thx, LGTM!

**Review by corwintines — APPROVED** [review]
